# This is a basic workflow to help you get started with Actions

name: Flutter CI for Web and Android

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master, develop, release ]
  pull_request:
    branches: [ master, develop, release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.2.0
      with:
        flutter-version: '1.12.13'
        channel: 'dev' # to support build for web
    
    - run: flutter pub get    # updates dependencies
    - run: flutter channel beta
    - run: flutter upgrade
    - run: flutter config --enable-web

    - run: flutter test       # runs tests
    - run: flutter build apk  # builds apk, ipa build not supported yet. Will update it in future
  # - run: flutter build web  # builds for web DISABLING IT FOR NOW. LOOKS LIKE IT IS NOT YET SUPPORTED.
