# This is a basic workflow to help you get started with Actions

name: Flutter CD for Web and Android

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.2.0
      with:
        flutter-version: '1.14.6'
        channel: 'beta' # to support build for web
        
    - run: flutter pub get    # updates dependencies
    - run: flutter upgrade
    - run: flutter config --enable-web
    - run: flutter build web
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
