name: Firebase Continuous Deployment

on:
  push:
    branches: [master, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Flutter Driver tests
      - run: flutter drive --target=test_driver/app.dart
      - run: flutter build web # building the web project for flutter
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
